# Generated by Django 4.2.2 on 2023-06-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginSystem', '0002_userotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_shipping', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='myAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userSystem.adress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginSystem.account')),
            ],
        ),
    ]
