# Generated by Django 4.2.2 on 2023-06-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myadress',
            name='adress',
        ),
        migrations.AddField(
            model_name='adress',
            name='myadress',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='userSystem.myadress'),
        ),
    ]
