# Generated by Django 4.2.2 on 2023-06-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0002_userotp'),
        ('userSystem', '0002_remove_myadress_adress_adress_myadress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='myadress',
        ),
        migrations.AddField(
            model_name='adress',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='loginSystem.account'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='city',
            field=models.CharField(default='city', max_length=50),
        ),
        migrations.AlterField(
            model_name='adress',
            name='country',
            field=models.CharField(default='country', max_length=50),
        ),
        migrations.AlterField(
            model_name='adress',
            name='pin',
            field=models.CharField(default='pin', max_length=50),
        ),
        migrations.AlterField(
            model_name='adress',
            name='state',
            field=models.CharField(default='state', max_length=50),
        ),
        migrations.DeleteModel(
            name='myAdress',
        ),
    ]
