# Generated by Django 4.2.2 on 2023-06-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0003_remove_adress_myadress_adress_user_alter_adress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='house',
            field=models.CharField(default='house', max_length=50),
        ),
    ]
