# Generated by Django 4.2.2 on 2023-06-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0005_pricerange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerange',
            name='max_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
