# Generated by Django 4.2.2 on 2023-06-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_rename_min_price_amount_coupon_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
