# Generated by Django 4.2.2 on 2023-06-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_discount_alter_coupon_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='released_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
