# Generated by Django 4.2.2 on 2023-06-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_coupon_released_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsedCoupon',
        ),
    ]
