# Generated by Django 4.2.2 on 2023-06-19 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=None)),
                ('is_available', models.BooleanField(default=True)),
                ('image1', models.ImageField(max_length=50, unique=True, upload_to='')),
                ('image2', models.ImageField(max_length=50, unique=True, upload_to='')),
                ('image3', models.ImageField(max_length=50, unique=True, upload_to='')),
                ('color_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.colorvariation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
