# Generated by Django 4.2.2 on 2023-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_name',
        ),
        migrations.AddField(
            model_name='product',
            name='color_variations',
            field=models.ManyToManyField(to='product.colorvariation'),
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
