# Generated by Django 4.2.2 on 2023-06-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_color_name_product_color_variations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_variations',
        ),
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.colorvariation'),
        ),
    ]
