# Generated by Django 4.2.2 on 2023-07-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0002_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
