# Generated by Django 4.2.2 on 2023-07-04 12:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0002_userotp'),
        ('mycart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='anonymous_user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loginSystem.account'),
        ),
    ]
