# Generated by Django 4.2.2 on 2023-06-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='main_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(max_length=50, unique=True, upload_to='')),
                ('main_head', models.TextField(unique=True)),
                ('main_description', models.TextField(max_length=100, unique=True)),
                ('image1', models.ImageField(max_length=50, unique=True, upload_to='')),
                ('price1', models.IntegerField(null=True, unique=True)),
                ('description1', models.TextField(max_length=100, unique=True)),
                ('image2', models.ImageField(max_length=50, unique=True, upload_to='')),
                ('price2', models.IntegerField(null=True, unique=True)),
                ('description2', models.TextField(default='', max_length=100, unique=True)),
                ('image3', models.ImageField(max_length=50, unique=True, upload_to='')),
                ('price3', models.IntegerField(null=True, unique=True)),
                ('description3', models.TextField(max_length=100, unique=True)),
            ],
        ),
    ]
