# Generated by Django 4.2.2 on 2023-06-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_ad',
            name='image1',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='main_ad',
            name='image2',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='main_ad',
            name='image3',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='main_ad',
            name='main_image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to=''),
        ),
    ]
