# Generated by Django 4.2.2 on 2023-06-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_time_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
