# Generated by Django 4.2.2 on 2023-06-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_coupon_usedcoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedcoupon',
            name='coupon',
        ),
        migrations.AddField(
            model_name='usedcoupon',
            name='coupon_used',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
