# Generated by Django 4.2.2 on 2023-06-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_usedcoupon_coupon_usedcoupon_coupon_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcoupon',
            name='coupon_used',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
